### ISSUE TITLE
Codemod errors when run as per Readme

### ISSUE THREAD

**Issue by kategengler** [ember-codemods/ember-native-class-codemod#138]
With my app running on localhost:4200, and running the codemod like so:

`npx ember-native-class-codemod http://localhost:4200/ app`

I see the following errors:

```
npx ember-native-class-codemod http://localhost:4200/ app
Downloading Chromium r669486 - 106.8 Mb [====================] 100% 0.0s
error evaluating `ember-composable-helpers/helpers/append`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/drop`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/flatten`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/intersect`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/join`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/reverse`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/shuffle`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/slice`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/take`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/union`: Cannot read property '1' of undefined
error evaluating `ember-moment/helpers/-base`: Cannot read property '1' of undefined
error evaluating `ember-moment/helpers/moment-format`: Cannot read property '1' of undefined
error evaluating `torii/load-initializers`: Could not find module `torii/initializers/initialize-torii` imported from `torii/load-initializers`
```

and then the codemod outputs an error: 

```
/Users/katie/.npm/_npx/20280/lib/node_modules/ember-native-class-codemod/node_modules/jsonfile/index.js:74
      throw err;
      ^

Error: tmp/broccoli_persistent_filtersimple_replace-input_base_path-IedTr0tn.tmp/package.json: ENOENT: no such file or directory, open 'tmp/broccoli_persistent_filtersimple_replace-input_base_path-IedTr0tn.tmp/package.json'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at Object.readFileSync (/Users/katie/.npm/_npx/20280/lib/node_modules/ember-native-class-codemod/node_modules/jsonfile/index.js:61:22)
    at Object.readJsonSync (/Users/katie/.npm/_npx/20280/lib/node_modules/ember-native-class-codemod/transforms/helpers/util/get-telemetry-for.js:16:16)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module._compile (/Users/katie/.npm/_npx/20280/lib/node_modules/ember-native-class-codemod/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.newLoader [as .js] (/Users/katie/.npm/_npx/20280/lib/node_modules/ember-native-class-codemod/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'tmp/broccoli_persistent_filtersimple_replace-input_base_path-IedTr0tn.tmp/package.json'
}
```

and then ends with:

```
All done.
Results:
0 errors
0 unmodified
0 skipped
0 ok

```

But nothing has been modified.

**Comment by lukemelia** [comment]
I experienced roughly the same thing trying to run it against my app.

**Comment by lukemelia** [comment]
Update: after updating to ember and ember-cli 3.10, and eliminating broccoli warnings, it still fails, but my errors are different:

```
➜  account git:(chore/native-classes) ✗ npx ember-native-class-codemod https://www.yapp.dev/account/checkout app/services/*
Downloading Chromium r669486 - 106.8 Mb [====================] 100% 0.0s
error evaluating `ember-animated/components/animated-beacon`: Found non-callable @@iterator
error evaluating `ember-animated/components/animated-container`: Found non-callable @@iterator
error evaluating `ember-animated/components/animated-each`: Found non-callable @@iterator
error evaluating `ember-animated/components/animated-orphans`: Found non-callable @@iterator
error evaluating `ember-animated/services/motion`: Found non-callable @@iterator
error evaluating `ember-composable-helpers/helpers/append`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/drop`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/flatten`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/intersect`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/join`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/reverse`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/shuffle`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/slice`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/take`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/union`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/index`: Could not find module `ember-composable-helpers/helpers/camelize` imported from `ember-composable-helpers/index`
error evaluating `ember-file-upload/mirage/index`: Could not find module `ember-cli-mirage/response` imported from `ember-file-upload/mirage/index`
error evaluating `ember-file-upload/queue`: Cannot read property '1' of undefined
error evaluating `ember-file-upload/services/file-queue`: Cannot read property '1' of undefined
error evaluating `ember-moment/helpers/-base`: Cannot read property '1' of undefined
error evaluating `ember-moment/helpers/moment-format`: Cannot read property '1' of undefined
error evaluating `ember-power-select/components/power-select`: Found non-callable @@iterator
error evaluating `yapp-ember-kit/components/fancy-dropdown/component`: Found non-callable @@iterator
error evaluating `yapp-ember-kit/components/invisible-efu-image-uploader/component`: Found non-callable @@iterator
error evaluating `yapp-ember-kit/mixins/css-animatable`: Found non-callable @@iterator
error evaluating `yapp-ember-kit/models/efu-upload`: Found non-callable @@iterator
error evaluating `yapp-ember-kit/services/transloadit-upload-support`: Cannot read property '1' of undefined
error evaluating `account/components/account-bar/unconfirmed-email-message/component`: Could not find module `yapp-ember-kit/components/account-bar/unconfirmed-email-message/component` imported from `account/components/account-bar/unconfirmed-email-message/component`
error evaluating `account/components/animated-beacon`: Found non-callable @@iterator
error evaluating `account/components/animated-container`: Found non-callable @@iterator
error evaluating `account/components/animated-each`: Found non-callable @@iterator
error evaluating `account/components/animated-orphans`: Found non-callable @@iterator
error evaluating `account/components/create-team-form/component`: Found non-callable @@iterator
error evaluating `account/components/fancy-dropdown/component`: Found non-callable @@iterator
error evaluating `account/components/invisible-efu-image-uploader`: Found non-callable @@iterator
error evaluating `account/components/power-select`: Found non-callable @@iterator
error evaluating `account/components/user-info/email-newsletter/component`: Found non-callable @@iterator
error evaluating `account/components/user-info/photo/component`: Found non-callable @@iterator
error evaluating `account/controllers/user/index`: Found non-callable @@iterator
error evaluating `account/helpers/acos`: Could not find module `ember-math-helpers/helpers/acos` imported from `account/helpers/acos`
error evaluating `account/helpers/acosh`: Could not find module `ember-math-helpers/helpers/acosh` imported from `account/helpers/acosh`
error evaluating `account/helpers/add`: Could not find module `ember-math-helpers/helpers/add` imported from `account/helpers/add`
error evaluating `account/helpers/append`: Cannot read property '1' of undefined
error evaluating `account/helpers/asin`: Could not find module `ember-math-helpers/helpers/asin` imported from `account/helpers/asin`
error evaluating `account/helpers/asinh`: Could not find module `ember-math-helpers/helpers/asinh` imported from `account/helpers/asinh`
error evaluating `account/helpers/atan`: Could not find module `ember-math-helpers/helpers/atan` imported from `account/helpers/atan`
error evaluating `account/helpers/atan2`: Could not find module `ember-math-helpers/helpers/atan2` imported from `account/helpers/atan2`
error evaluating `account/helpers/atanh`: Could not find module `ember-math-helpers/helpers/atanh` imported from `account/helpers/atanh`
error evaluating `account/helpers/camelize`: Could not find module `ember-cli-string-helpers/helpers/camelize` imported from `account/helpers/camelize`
error evaluating `account/helpers/capitalize`: Could not find module `ember-cli-string-helpers/helpers/capitalize` imported from `account/helpers/capitalize`
error evaluating `account/helpers/cbrt`: Could not find module `ember-math-helpers/helpers/cbrt` imported from `account/helpers/cbrt`
error evaluating `account/helpers/ceil`: Could not find module `ember-math-helpers/helpers/ceil` imported from `account/helpers/ceil`
error evaluating `account/helpers/classify`: Could not find module `ember-cli-string-helpers/helpers/classify` imported from `account/helpers/classify`
error evaluating `account/helpers/clz32`: Could not find module `ember-math-helpers/helpers/clz32` imported from `account/helpers/clz32`
error evaluating `account/helpers/cos`: Could not find module `ember-math-helpers/helpers/cos` imported from `account/helpers/cos`
error evaluating `account/helpers/cosh`: Could not find module `ember-math-helpers/helpers/cosh` imported from `account/helpers/cosh`
error evaluating `account/helpers/dasherize`: Could not find module `ember-cli-string-helpers/helpers/dasherize` imported from `account/helpers/dasherize`
error evaluating `account/helpers/div`: Could not find module `ember-math-helpers/helpers/div` imported from `account/helpers/div`
error evaluating `account/helpers/drop`: Cannot read property '1' of undefined
error evaluating `account/helpers/exp`: Could not find module `ember-math-helpers/helpers/exp` imported from `account/helpers/exp`
error evaluating `account/helpers/expm1`: Could not find module `ember-math-helpers/helpers/expm1` imported from `account/helpers/expm1`
error evaluating `account/helpers/flatten`: Cannot read property '1' of undefined
error evaluating `account/helpers/floor`: Could not find module `ember-math-helpers/helpers/floor` imported from `account/helpers/floor`
error evaluating `account/helpers/fround`: Could not find module `ember-math-helpers/helpers/fround` imported from `account/helpers/fround`
error evaluating `account/helpers/gcd`: Could not find module `ember-math-helpers/helpers/gcd` imported from `account/helpers/gcd`
error evaluating `account/helpers/html-safe`: Could not find module `ember-cli-string-helpers/helpers/html-safe` imported from `account/helpers/html-safe`
error evaluating `account/helpers/humanize`: Could not find module `ember-cli-string-helpers/helpers/humanize` imported from `account/helpers/humanize`
error evaluating `account/helpers/hypot`: Could not find module `ember-math-helpers/helpers/hypot` imported from `account/helpers/hypot`
error evaluating `account/helpers/imul`: Could not find module `ember-math-helpers/helpers/imul` imported from `account/helpers/imul`
error evaluating `account/helpers/intersect`: Cannot read property '1' of undefined
error evaluating `account/helpers/join`: Cannot read property '1' of undefined
error evaluating `account/helpers/lcm`: Could not find module `ember-math-helpers/helpers/lcm` imported from `account/helpers/lcm`
error evaluating `account/helpers/log-e`: Could not find module `ember-math-helpers/helpers/log-e` imported from `account/helpers/log-e`
error evaluating `account/helpers/log10`: Could not find module `ember-math-helpers/helpers/log10` imported from `account/helpers/log10`
error evaluating `account/helpers/log1p`: Could not find module `ember-math-helpers/helpers/log1p` imported from `account/helpers/log1p`
error evaluating `account/helpers/log2`: Could not find module `ember-math-helpers/helpers/log2` imported from `account/helpers/log2`
error evaluating `account/helpers/lowercase`: Could not find module `ember-cli-string-helpers/helpers/lowercase` imported from `account/helpers/lowercase`
error evaluating `account/helpers/mod`: Could not find module `ember-math-helpers/helpers/mod` imported from `account/helpers/mod`
error evaluating `account/helpers/moment-format`: Cannot read property '1' of undefined
error evaluating `account/helpers/mult`: Could not find module `ember-math-helpers/helpers/mult` imported from `account/helpers/mult`
error evaluating `account/helpers/pow`: Could not find module `ember-math-helpers/helpers/pow` imported from `account/helpers/pow`
error evaluating `account/helpers/random`: Could not find module `ember-math-helpers/helpers/random` imported from `account/helpers/random`
error evaluating `account/helpers/reverse`: Cannot read property '1' of undefined
error evaluating `account/helpers/round`: Could not find module `ember-math-helpers/helpers/round` imported from `account/helpers/round`
error evaluating `account/helpers/shuffle`: Cannot read property '1' of undefined
error evaluating `account/helpers/sign`: Could not find module `ember-math-helpers/helpers/sign` imported from `account/helpers/sign`
error evaluating `account/helpers/sin`: Could not find module `ember-math-helpers/helpers/sin` imported from `account/helpers/sin`
error evaluating `account/helpers/slice`: Cannot read property '1' of undefined
error evaluating `account/helpers/sqrt`: Could not find module `ember-math-helpers/helpers/sqrt` imported from `account/helpers/sqrt`
error evaluating `account/helpers/sub`: Could not find module `ember-math-helpers/helpers/sub` imported from `account/helpers/sub`
error evaluating `account/helpers/take`: Cannot read property '1' of undefined
error evaluating `account/helpers/tan`: Could not find module `ember-math-helpers/helpers/tan` imported from `account/helpers/tan`
error evaluating `account/helpers/tanh`: Could not find module `ember-math-helpers/helpers/tanh` imported from `account/helpers/tanh`
error evaluating `account/helpers/titleize`: Could not find module `ember-cli-string-helpers/helpers/titleize` imported from `account/helpers/titleize`
error evaluating `account/helpers/trim`: Could not find module `ember-cli-string-helpers/helpers/trim` imported from `account/helpers/trim`
error evaluating `account/helpers/trunc`: Could not find module `ember-math-helpers/helpers/trunc` imported from `account/helpers/trunc`
error evaluating `account/helpers/truncate`: Could not find module `ember-cli-string-helpers/helpers/truncate` imported from `account/helpers/truncate`
error evaluating `account/helpers/underscore`: Could not find module `ember-cli-string-helpers/helpers/underscore` imported from `account/helpers/underscore`
error evaluating `account/helpers/union`: Cannot read property '1' of undefined
error evaluating `account/helpers/uppercase`: Could not find module `ember-cli-string-helpers/helpers/uppercase` imported from `account/helpers/uppercase`
error evaluating `account/models/efu-upload`: Found non-callable @@iterator
error evaluating `account/services/-ea-motion`: Found non-callable @@iterator
error evaluating `account/services/file-queue`: Cannot read property '1' of undefined
error evaluating `account/services/transloadit-upload-support`: Cannot read property '1' of undefined
error evaluating `account/transitions/fade-direction`: Could not find module `liquid-fire` imported from `account/transitions/fade-direction`
error evaluating `account/transitions/fade-down`: Cannot read property 'exports' of undefined
error evaluating `account/transitions/fade-up`: Cannot read property 'exports' of undefined
Processing 19 files...
Spawning 3 workers...
Sending 7 files to free worker...
Sending 7 files to free worker...
Sending 5 files to free worker...
/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:33
      throw error;
      ^

Error: ENOTDIR: not a directory, stat './/tmp/funnel-output_path-0JFXoYOf.tmp/regenerator-runtime'
    at Object.statSync (fs.js:851:3)
    at statSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:23:19)
    at getStat (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:130:25)
    at Array.map (<anonymous>)
    at map (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:124:29)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:145:42)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:145:42)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:19:12)
    at Object.walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/transforms/helpers/util/get-telemetry-for.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:33
      throw error;
      ^

Error: ENOTDIR: not a directory, stat './/tmp/funnel-output_path-0JFXoYOf.tmp/regenerator-runtime'
    at Object.statSync (fs.js:851:3)
    at statSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:23:19)
    at getStat (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:130:25)
    at Array.map (<anonymous>)
    at map (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:124:29)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:145:42)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:145:42)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:19:12)
    at Object.walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/transforms/helpers/util/get-telemetry-for.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:33
      throw error;
      ^

Error: ENOTDIR: not a directory, stat './/tmp/funnel-output_path-0JFXoYOf.tmp/regenerator-runtime'
    at Object.statSync (fs.js:851:3)
    at statSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:23:19)
    at getStat (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:130:25)
    at Array.map (<anonymous>)
    at map (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:124:29)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:145:42)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:145:42)
    at _walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/node_modules/walk-sync/index.js:19:12)
    at Object.walkSync (/Users/lmelia/.npm/_npx/12124/lib/node_modules/ember-native-class-codemod/transforms/helpers/util/get-telemetry-for.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
All done.
Results:
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 17.818seconds
```

**Comment by rwjblue** [comment]
The `error evaluating ‘some/module/here’` is a warning that the specific modules could not be required, and so we couldn’t gather runtime telemetry data for those modules. It **should** be “fine” (those modules won’t be converted but it should continue to work for others).

The real issue (as @lukemelia ultimately identified) is that `walkSync` is attempting to walk all of the files in the project (when we attempt to find all of the `package.json`’s in the project for mapping the telemetry back with the on disk paths) and if `walkSync` finds a broken symlink it is erroring. 

I suspect that we can likely avoid walking `tmp/` (`node_modules/` too while we are at it) and avoid the largest vector for this (though not all of them).

**Comment by rwjblue** [comment]
Can y'all test v1.0.1 (includes https://github.com/ember-codemods/ember-native-class-codemod/pull/140)?

**Comment by kategengler** [comment]
Still got a bunch of 
```
error evaluating `ember-composable-helpers/helpers/shuffle`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/slice`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/take`: Cannot read property '1' of undefined
error evaluating `ember-composable-helpers/helpers/union`: Cannot read property '1' of undefined
```  but it worked :tada:

**Comment by rwjblue** [comment]
@kategengler - Ya, I'm working on refactoring those warnings to be much more approachable. They are "expected", but the message is horrible.

**Comment by lukemelia** [comment]
Succeeded for me too. "@service" decorators were doubled up, but I'll create a separate issue for that.

**Comment by rwjblue** [comment]
Thanks @lukemelia

**Comment by rwjblue** [comment]
I'll close this one then, and we can create/track the other poor ux issues in separate issues.

**Comment by Alonski** [comment]
I am running into something similar:
I am running into an issue locally when running telemetry. Not sure how to start debugging this.
This is the command I am running:
`npx ember-native-class-codemod http://localhost:4201/style-guide?s=Modal .\addon\components\modal\modal-c1.js`
Getting a bunch of:
`error evaluating dummy/services/file-queue: Cannot read property '1' of undefined`
Then finally:
```
(node:28840) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir 'C:\Users\Alon\AppData\Local\Temp\Alon\if-you-need-to-delete-this-open-an-issue-sync-disk-cache'
    at Object.mkdirSync (fs.js:757:3)
    at sync (C:\Users\Alon\AppData\Roaming\npm-cache\_npx\28840\node_modules\ember-native-class-codemod\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\Alon\AppData\Roaming\npm-cache\_npx\28840\node_modules\ember-native-class-codemod\node_modules\mkdirp\index.js:78:17)
(node:28840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
On Windows 10 :slight_smile:
