### ISSUE TITLE
Error `Cannot read property 'from' of undefined`

### ISSUE THREAD

**Issue by YoranBrondsema** [ember-codemods/ember-native-class-codemod#291]
For the last few days, I keep getting the following error whenever I run `ember-native-class-codemod`:

```
> npx --no-install ember-native-class-codemod http://localhost:4200 "/home/yoran/Projects/sutori/frontend/app/components/modal-story-templates/component.js"

error evaluating `torii/load-initializers`: Could not find module `torii/initializers/initialize-torii` imported from `torii/load-initializers`
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
/home/yoran/Projects/sutori/frontend/node_modules/@babel/core/lib/transformation/index.js:66
    throw e;
    ^

TypeError: /home/yoran/Projects/sutori/frontend/node_modules/safe-buffer/index.js: Cannot read property 'from' of undefined
    at Converter.toBase64 (/home/yoran/Projects/sutori/frontend/node_modules/convert-source-map/index.js:61:28)
    at Converter.toComment (/home/yoran/Projects/sutori/frontend/node_modules/convert-source-map/index.js:65:21)
    at generateCode (/home/yoran/Projects/sutori/frontend/node_modules/@babel/core/lib/transformation/file/generate.js:78:76)
    at run (/home/yoran/Projects/sutori/frontend/node_modules/@babel/core/lib/transformation/index.js:55:33)
    at run.next (<anonymous>)
    at Function.transform (/home/yoran/Projects/sutori/frontend/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>)
    at evaluateSync (/home/yoran/Projects/sutori/frontend/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/yoran/Projects/sutori/frontend/node_modules/gensync/index.js:84:14)
    at Object.transform (/home/yoran/Projects/sutori/frontend/node_modules/@babel/core/lib/transform.js:36:54) {
  code: 'BABEL_GENERATE_ERROR'
}
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.360seconds
```

It was working before. Since the latest release of `ember-native-class-codemod` is from August 2019, I think that it must be a dependency that has updated and causing the error.

Any thoughts?

**Comment by YoranBrondsema** [comment]
Looks like a duplicate of https://github.com/ember-codemods/ember-angle-brackets-codemod/issues/195
