### ISSUE TITLE
TypeError: Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by sarbbottam** [ember-codemods/ember-native-class-codemod#314]
```
npx ember-native-class-codemod https://<host>:<port>/path/ app/**/*.js
```

The process hangs after the following error.

```
Downloading Chromium r686378 - 110.2 Mb [====================] 100% 0.0s 
(node:58858) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'entries' of undefined
    at __puppeteer_evaluation_script__:7:48
    at ExecutionContext._evaluateInternal (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async gatherTelemetry (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/ember-codemods-telemetry-helpers/lib/gather/gather-telemetry.js:15:21)
    at async /Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/bin/cli.js:7:3
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/helper.js:112:23)
    at gatherTelemetry (/Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/node_modules/ember-codemods-telemetry-helpers/lib/gather/gather-telemetry.js:15:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/sabandyo/.npm/_npx/58858/lib/node_modules/ember-native-class-codemod/bin/cli.js:7:3
(node:58858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:58858) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rwjblue** [comment]
I suspect what is happening is that the browser we are launching is not actually ending up on the Ember application. Often times this is due to being redirected to an external login page, or something like that.

Maybe you could navigate to `/tests` instead of your main application landing page?

**Comment by basz** [comment]
I'm seeing this as well. Pointing to a different path isn't any different... My app isn't redirecting either...

a `yarn global remove/add` of ember-native-class-codemod@1.1.0 did not help

**Comment by sarbbottam** [comment]
As suggested by @rwjblue `npx ember-native-class-codemod https://<host>:<port>/tests/ app/**/*.js` worked for me.

**Comment by basz** [comment]
Well it does not for me... :) can we reopen?

**Comment by sarbbottam** [comment]
Reopened as requested by @basz.

**Comment by TomaszWegrzyn** [comment]
Above problem is the same as in #242, I believe they just need to update `ember-codemods-telemetry-helpers` in order to fix it.

**Comment by rjschie** [comment]
I was getting this error as well and found it was due to the use of optional chaining in our apps and building to targets of `last 1 Chrome versions`.

This depends on puppeteer@1.20.0 which uses Chrome 78 and optional chaining was added in Chrome 80.

Upgrading this to puppeteer@latest worked for me to be able to run my code. I've [opened a PR](https://github.com/ember-codemods/ember-codemods-telemetry-helpers/pull/32) as well.

**Comment by jelhan** [comment]
This error seems to have different causes. For me disabling fastboot on the ember serve instance helped: `FASTBOOT_DISABLED=true ember serve`.

**Comment by BryanCrotaz** [comment]
I'm getting this error with
node v12.16.1 (happens in node 9 and 10 too)
It's downloading chromium r686378
