### ISSUE TITLE
Error `Error: Evaluation failed: TypeError: Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by YoranBrondsema** [ember-codemods/ember-native-class-codemod#343]
I'm attempting to run the codemod on a component in my app but I'm getting an error with (I think) puppeteer. Any thoughts about what might be going wrong?

```
yoran $ npx ember-native-class-codemod http://localhost:4200 app/components/inplace-editor/component.js 
Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
(node:24366) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at __puppeteer_evaluation_script__:7:28
    at ExecutionContext._evaluateInternal (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async gatherTelemetry (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/ember-codemods-telemetry-helpers/lib/gather/gather-telemetry.js:15:21)
    at async /home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/bin/cli.js:7:3
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/puppeteer/lib/helper.js:112:23)
    at gatherTelemetry (/home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/node_modules/ember-codemods-telemetry-helpers/lib/gather/gather-telemetry.js:15:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/yoran/.npm/_npx/24366/lib/node_modules/ember-native-class-codemod/bin/cli.js:7:3
(node:24366) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24366) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by candunaj** [comment]
I have exactly the same error.
