### ISSUE TITLE
TypeError: Cannot read property 'process' of undefined

### ISSUE THREAD

**Issue by lifeart** [ember-codemods/ember-native-class-codemod#392]
TypeError: Cannot read property 'process' of undefined
    at C:\Users\lifeart\AppData\Roaming\npm-cache\_npx\173988\node_modules\ember-es6-class-codemod\node_modules\flow-parser\/flow_parser.js:281:70
    at Object.<anonymous> (C:\Users\lifeart\AppData\Roaming\npm-cache\_npx\173988\node_modules\ember-es6-class-codemod\node_modules\flow-parser\/flow_parser.js:2:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (C:\Users\lifeart\AppData\Roaming\npm-cache\_npx\173988\node_modules\ember-es6-class-codemod\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (C:\Users\lifeart\AppData\Roaming\npm-cache\_npx\173988\node_modules\ember-es6-class-codemod\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by lifeart** [comment]
looks related: https://github.com/reactjs/react-codemod/issues/219

**Comment by JoepHeijnen** [comment]
I tried the solutions in the related issues, but i am still getting this error. 

I tried different variations of the following command line.
`npx ember-native-class-codemod http://localhost:4200 --no-babel app/components`

Am i missing something or does ember-native-class-codemod not support these flags?

**Comment by lifeart** [comment]
@JoepHeijnen ya, flags not working

**Comment by IsakFriisJespersen2** [comment]
Is there any solution to this one?
